name: 压缩脚本

on:
  pull_request:
    paths:
    - psnineplus.js
    branches: [ master ]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 自动压缩
      uses: nizarmah/auto-minify@master
    - name: 自动提交所生成的压缩文件
      uses: stefanzweifel/git-auto-commit-action@v3.0.0
      with:
        commit_message: "Github Action: 生成压缩文件"
        branch: ${{ github.ref }}